[target.thumbv7m-none-eabi]
# uncomment this to make `cargo run` execute programs on QEMU
runner = "qemu-system-arm -machine stm32vldiscovery -cpu cortex-m3 -nographic -semihosting-config enable=on,target=native -kernel"
